apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.moduleName }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    module: {{ .Values.moduleName }}
spec:
  selector:
    module: {{ .Values.moduleName }}
  type: {{ .Values.service.ontologyManager.type }}
  ports:
    - name: {{ .Values.moduleName }}
      port: {{ .Values.service.ontologyManager.port }}
      protocol: TCP
      targetPort: manager
      {{- if eq .Values.service.ontologyManager.type "NodePort" }}
      nodePort: {{ .Values.service.ontologyManager.nodePort }}
      {{- end }}